"use client";

import {
  ArrowsClockwise,
  Copy,
  Eye,
  EyeSlash,
  Key,
  Lock,
  ShieldCheck,
  Trash,
  UploadSimple,
  Warning,
} from "@phosphor-icons/react";
import {
  type ChangeEvent,
  type ClipboardEvent,
  type Dispatch,
  type DragEvent,
  type SetStateAction,
  useCallback,
  useEffect,
  useState,
} from "react";

import { storeEnvelopeFromClientAction } from "@/actions/envelope-actions";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { CopyButton } from "@/components/ui/copy-button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";
import { Textarea } from "@/components/ui/textarea";
import { createEnvironmentEnvelope } from "@/lib/crypto/primitives";

interface EnvVariable {
  id: string;
  key: string;
  value: string;
}

interface ParsedEnvVariable {
  key: string;
  value: string;
}

type EncryptionState = "done" | "encrypting" | "error" | "idle";
type ImportSource = "clipboard" | "file" | "manual";

const MIN_PASSPHRASE_LENGTH = 12;
const DEFAULT_AUTO_PASSPHRASE_LENGTH = 24;
const PASS_CHARSET =
  "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*()-_=+";
const FALLBACK_AUTOGENERATED_PASSPHRASE = "Vault-Local-Secret-2026!";
const HAS_UPPERCASE_REGEX = /[A-Z]/;
const HAS_LOWERCASE_REGEX = /[a-z]/;
const HAS_DIGIT_REGEX = /\d/;
const HAS_SYMBOL_REGEX = /[^A-Za-z0-9]/;
const ENV_ASSIGNMENT_REGEX = /^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/;
const INLINE_ENV_COMMENT_REGEX = /\s+#/;
const ENV_LINE_SPLIT_REGEX = /\r?\n/u;
const ENV_EXPORT_PREFIX_REGEX = /^export\s+/u;
let envVariableIdCounter = 0;

const createVariableId = (): string => {
  envVariableIdCounter += 1;
  return `env-var-${String(envVariableIdCounter)}`;
};

const decodeDoubleQuotedEnvValue = (value: string): string =>
  value.replace(/\\([nrt"\\])/g, (fullMatch, group: string) => {
    if (group === "n") {
      return "\n";
    }

    if (group === "r") {
      return "\r";
    }

    if (group === "t") {
      return "\t";
    }

    if (group === '"') {
      return '"';
    }

    if (group === "\\") {
      return "\\";
    }

    return fullMatch;
  });

const normalizeEnvValue = (rawValue: string): string => {
  const trimmed = rawValue.trim();

  if (trimmed.length >= 2) {
    const firstCharacter = trimmed.at(0);
    const lastCharacter = trimmed.at(-1);

    if (firstCharacter === '"' && lastCharacter === '"') {
      return decodeDoubleQuotedEnvValue(trimmed.slice(1, -1));
    }

    if (firstCharacter === "'" && lastCharacter === "'") {
      return trimmed.slice(1, -1);
    }
  }

  const inlineCommentIndex = trimmed.search(INLINE_ENV_COMMENT_REGEX);
  if (inlineCommentIndex === -1) {
    return trimmed;
  }

  return trimmed.slice(0, inlineCommentIndex).trimEnd();
};

const parseBulkEnvInput = (
  rawInput: string
): { invalidLineCount: number; variables: ParsedEnvVariable[] } => {
  const parsedVariables: ParsedEnvVariable[] = [];
  let invalidLineCount = 0;

  for (const rawLine of rawInput.split(ENV_LINE_SPLIT_REGEX)) {
    const trimmedLine = rawLine.trim();

    if (trimmedLine.length === 0 || trimmedLine.startsWith("#")) {
      continue;
    }

    const normalizedLine = trimmedLine.replace(ENV_EXPORT_PREFIX_REGEX, "");
    const match = normalizedLine.match(ENV_ASSIGNMENT_REGEX);

    if (!match) {
      invalidLineCount += 1;
      continue;
    }

    const key = match[1]?.trim();
    if (!key) {
      invalidLineCount += 1;
      continue;
    }

    parsedVariables.push({
      key,
      value: normalizeEnvValue(match[2] ?? ""),
    });
  }

  return {
    invalidLineCount,
    variables: parsedVariables,
  };
};

const mergeImportedVariables = (
  existingVariables: EnvVariable[],
  importedVariables: ParsedEnvVariable[]
): EnvVariable[] => {
  if (importedVariables.length === 0) {
    return existingVariables;
  }

  const mergedVariables = existingVariables.map((variable) => ({
    ...variable,
  }));
  const hasFilledValues = mergedVariables.some(
    (variable) =>
      variable.key.trim().length > 0 || variable.value.trim().length > 0
  );

  const keyToIndex = new Map<string, number>();
  for (const [index, variable] of mergedVariables.entries()) {
    const existingKey = variable.key.trim();
    if (existingKey.length > 0 && !keyToIndex.has(existingKey)) {
      keyToIndex.set(existingKey, index);
    }
  }

  let importStartIndex = 0;
  if (!hasFilledValues && mergedVariables.length === 1) {
    const firstImport = importedVariables.at(0);
    if (firstImport) {
      mergedVariables[0] = {
        ...mergedVariables[0],
        key: firstImport.key,
        value: firstImport.value,
      };
      keyToIndex.set(firstImport.key, 0);
      importStartIndex = 1;
    }
  }

  for (const importedVariable of importedVariables.slice(importStartIndex)) {
    const existingIndex = keyToIndex.get(importedVariable.key);

    if (existingIndex !== undefined) {
      mergedVariables[existingIndex] = {
        ...mergedVariables[existingIndex],
        key: importedVariable.key,
        value: importedVariable.value,
      };
      continue;
    }

    mergedVariables.push({
      id: createVariableId(),
      key: importedVariable.key,
      value: importedVariable.value,
    });
    keyToIndex.set(importedVariable.key, mergedVariables.length - 1);
  }

  return mergedVariables;
};

const hasRequiredCharacterClasses = (value: string): boolean =>
  HAS_UPPERCASE_REGEX.test(value) &&
  HAS_LOWERCASE_REGEX.test(value) &&
  HAS_DIGIT_REGEX.test(value) &&
  HAS_SYMBOL_REGEX.test(value);

const generateSecurePassphrase = (
  length: number = DEFAULT_AUTO_PASSPHRASE_LENGTH
): string => {
  const cryptoObject = globalThis.crypto;
  if (!cryptoObject?.getRandomValues) {
    return FALLBACK_AUTOGENERATED_PASSPHRASE;
  }

  for (let attempt = 0; attempt < 5; attempt += 1) {
    const randomValues = new Uint32Array(length);
    cryptoObject.getRandomValues(randomValues);
    const generated = Array.from(
      randomValues,
      (value) => PASS_CHARSET[value % PASS_CHARSET.length]
    ).join("");

    if (
      generated.length >= MIN_PASSPHRASE_LENGTH &&
      hasRequiredCharacterClasses(generated)
    ) {
      return generated;
    }
  }

  return FALLBACK_AUTOGENERATED_PASSPHRASE;
};

const getDuplicateVariableKeys = (variables: EnvVariable[]): string[] => {
  const seenKeys = new Set<string>();
  const duplicateKeys = new Set<string>();

  for (const variable of variables) {
    const key = variable.key.trim();
    if (key.length === 0) {
      continue;
    }

    if (seenKeys.has(key)) {
      duplicateKeys.add(key);
      continue;
    }

    seenKeys.add(key);
  }

  return Array.from(duplicateKeys);
};

const buildEnvironmentMap = (
  variables: EnvVariable[]
): Record<string, string> => {
  const envMap: Record<string, string> = {};

  for (const variable of variables) {
    const key = variable.key.trim();
    const value = variable.value.trim();

    if (key.length > 0 && value.length > 0) {
      envMap[key] = value;
    }
  }

  return envMap;
};

const getStrengthToneClass = (label: string): string => {
  if (label === "Strong") {
    return "text-primary";
  }
  if (label === "Good") {
    return "text-yellow-500";
  }
  if (label === "Weak") {
    return "text-orange-500";
  }
  return "text-muted-foreground";
};

const getPassphraseStrength = (
  passphrase: string
): { color: string; label: string; percent: number } => {
  const length = passphrase.length;
  if (length === 0) {
    return { label: "", percent: 0, color: "bg-muted" };
  }
  if (length < MIN_PASSPHRASE_LENGTH) {
    return { label: "Too short", percent: 20, color: "bg-destructive" };
  }

  let score = 0;
  if (length >= 16) {
    score += 1;
  }
  if (length >= 24) {
    score += 1;
  }
  if (
    HAS_UPPERCASE_REGEX.test(passphrase) &&
    HAS_LOWERCASE_REGEX.test(passphrase)
  ) {
    score += 1;
  }
  if (HAS_DIGIT_REGEX.test(passphrase)) {
    score += 1;
  }
  if (HAS_SYMBOL_REGEX.test(passphrase)) {
    score += 1;
  }

  if (score <= 1) {
    return { label: "Weak", percent: 40, color: "bg-orange-500" };
  }
  if (score <= 3) {
    return { label: "Good", percent: 70, color: "bg-yellow-500" };
  }
  return { label: "Strong", percent: 100, color: "bg-primary" };
};

const getImportSourceLabel = (source: ImportSource): string => {
  if (source === "file") {
    return ".env file";
  }

  if (source === "clipboard") {
    return "clipboard";
  }

  return "pasted text";
};

const getEncryptValidationMessage = (
  duplicateKeys: string[],
  canEncrypt: boolean
): string | null => {
  if (duplicateKeys.length > 0) {
    return `Duplicate key${duplicateKeys.length > 1 ? "s" : ""} found: ${duplicateKeys.slice(0, 3).join(", ")}`;
  }

  if (!canEncrypt) {
    return "Add at least one complete variable and use a stronger passphrase.";
  }

  return null;
};

const getKdfConfiguration = () => ({
  name: "Argon2id" as const,
  iterations: 3,
  memoryKiB: 65_536,
  parallelism: 1,
  outputLength: 64,
});

const useBulkEnvImport = ({
  setValidationMessage,
  setVariables,
}: {
  setValidationMessage: Dispatch<SetStateAction<string | null>>;
  setVariables: Dispatch<SetStateAction<EnvVariable[]>>;
}) => {
  const [bulkImportInput, setBulkImportInput] = useState("");
  const [importMessage, setImportMessage] = useState<string | null>(null);
  const [uploadedFileName, setUploadedFileName] = useState<string | null>(null);

  const applyImportedVariables = useCallback(
    (rawInput: string, source: ImportSource, sourceFileName?: string) => {
      const { invalidLineCount, variables: parsedVariables } =
        parseBulkEnvInput(rawInput);

      if (parsedVariables.length === 0) {
        setImportMessage(null);
        setValidationMessage(
          "No valid KEY=VALUE lines detected. Paste .env or Vercel-style variables."
        );
        return;
      }

      setVariables((prev) => mergeImportedVariables(prev, parsedVariables));
      setValidationMessage(null);

      if (source === "file") {
        setBulkImportInput(rawInput);
        setUploadedFileName(sourceFileName ?? "uploaded.env");
      } else {
        setBulkImportInput("");
        setUploadedFileName(null);
      }

      const sourceLabel = getImportSourceLabel(source);
      const skippedLineSuffix =
        invalidLineCount > 0
          ? ` (${String(invalidLineCount)} invalid line${invalidLineCount === 1 ? "" : "s"} skipped)`
          : "";

      setImportMessage(
        `Imported ${String(parsedVariables.length)} variable${parsedVariables.length === 1 ? "" : "s"} from ${sourceLabel}${skippedLineSuffix}.`
      );
    },
    [setValidationMessage, setVariables]
  );

  const handleImportFromTextarea = useCallback(() => {
    if (bulkImportInput.trim().length === 0) {
      setValidationMessage("Paste one or more KEY=VALUE lines to import.");
      setImportMessage(null);
      return;
    }

    applyImportedVariables(bulkImportInput, "manual");
  }, [applyImportedVariables, bulkImportInput, setValidationMessage]);

  const handleBulkImportPaste = useCallback(
    (event: ClipboardEvent<HTMLTextAreaElement>) => {
      const pastedText = event.clipboardData.getData("text");

      if (pastedText.trim().length === 0) {
        return;
      }

      event.preventDefault();
      applyImportedVariables(pastedText, "clipboard");
    },
    [applyImportedVariables]
  );

  const importFromFile = useCallback(
    async (file: File) => {
      try {
        const fileContents = await file.text();
        applyImportedVariables(fileContents, "file", file.name);
      } catch {
        setImportMessage(null);
        setValidationMessage("Could not read the selected .env file.");
      }
    },
    [applyImportedVariables, setValidationMessage]
  );

  const handleEnvFileUpload = useCallback(
    async (event: ChangeEvent<HTMLInputElement>) => {
      const selectedFile = event.target.files?.[0];
      if (!selectedFile) {
        return;
      }

      await importFromFile(selectedFile);
      event.target.value = "";
    },
    [importFromFile]
  );

  const handleDroppedEnvFile = useCallback(
    async (file: File) => {
      await importFromFile(file);
    },
    [importFromFile]
  );

  const resetBulkImportState = useCallback(() => {
    setBulkImportInput("");
    setImportMessage(null);
    setUploadedFileName(null);
  }, []);

  return {
    bulkImportInput,
    handleDroppedEnvFile,
    handleBulkImportPaste,
    handleEnvFileUpload,
    handleImportFromTextarea,
    importMessage,
    resetBulkImportState,
    setBulkImportInput,
    uploadedFileName,
  };
};

interface EnvironmentVariablesSectionProps {
  bulkImportInput: string;
  importMessage: string | null;
  onBulkImportPaste: (event: ClipboardEvent<HTMLTextAreaElement>) => void;
  onDroppedEnvFile: (file: File) => Promise<void>;
  onEnvFileUpload: (event: ChangeEvent<HTMLInputElement>) => void;
  onImportFromTextarea: () => void;
  onRemoveVariable: (id: string) => void;
  setBulkImportInput: Dispatch<SetStateAction<string>>;
  uploadedFileName: string | null;
  variables: EnvVariable[];
}

function EnvironmentVariablesSection({
  bulkImportInput,
  importMessage,
  onDroppedEnvFile,
  onBulkImportPaste,
  onEnvFileUpload,
  onImportFromTextarea,
  onRemoveVariable,
  setBulkImportInput,
  uploadedFileName,
  variables,
}: EnvironmentVariablesSectionProps) {
  const [visibleVariableIds, setVisibleVariableIds] = useState<Set<string>>(
    () => new Set()
  );
  const [isDraggingOverDropzone, setIsDraggingOverDropzone] = useState(false);
  const fileUploadInputId = "encrypt-env-upload-input";

  const toggleVariableVisibility = useCallback((id: string) => {
    setVisibleVariableIds((previousIds) => {
      const nextIds = new Set(previousIds);

      if (nextIds.has(id)) {
        nextIds.delete(id);
      } else {
        nextIds.add(id);
      }

      return nextIds;
    });
  }, []);

  const handleDropzoneDragOver = useCallback(
    (event: DragEvent<HTMLButtonElement>) => {
      event.preventDefault();
      event.dataTransfer.dropEffect = "copy";
      setIsDraggingOverDropzone(true);
    },
    []
  );

  const handleDropzoneDragLeave = useCallback(() => {
    setIsDraggingOverDropzone(false);
  }, []);

  const handleDropzoneDrop = useCallback(
    async (event: DragEvent<HTMLButtonElement>) => {
      event.preventDefault();
      setIsDraggingOverDropzone(false);

      const droppedFile = event.dataTransfer.files?.[0];
      if (!droppedFile) {
        return;
      }

      await onDroppedEnvFile(droppedFile);
    },
    [onDroppedEnvFile]
  );

  const handleDropzoneClick = useCallback(() => {
    const inputElement = document.getElementById(
      fileUploadInputId
    ) as HTMLInputElement | null;
    inputElement?.click();
  }, []);

  return (
    <div className="space-y-4 rounded-2xl border border-border/80 bg-card/60 p-5 md:p-6">
      <div className="flex items-center justify-between">
        <Label className="font-medium text-sm">Environment Variables</Label>
        <Badge
          className="rounded-full border-primary/35 px-3 py-0.5"
          variant="outline"
        >
          {String(variables.length)} row{variables.length === 1 ? "" : "s"}
        </Badge>
      </div>

      <div className="space-y-3">
        <div className="space-y-4 rounded-2xl border border-border/70 border-dashed bg-background/45 p-3 md:p-4">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <Label className="font-medium text-xs uppercase tracking-wider">
              Quick Import
            </Label>
            <Badge className="rounded-full px-3 py-0.5" variant="secondary">
              .env + Vercel format
            </Badge>
          </div>

          <button
            className={`flex w-full items-center justify-between gap-3 rounded-xl border px-3 py-3 text-left transition-colors ${
              isDraggingOverDropzone
                ? "border-primary/70 bg-primary/10"
                : "border-border/70 bg-background/70 hover:border-primary/40"
            }`}
            onClick={handleDropzoneClick}
            onDragLeave={handleDropzoneDragLeave}
            onDragOver={handleDropzoneDragOver}
            onDrop={handleDropzoneDrop}
            type="button"
          >
            <span className="flex items-center gap-2 text-muted-foreground text-xs">
              <span className="flex size-8 items-center justify-center rounded-full bg-primary/15 text-primary">
                <UploadSimple className="size-4" weight="bold" />
              </span>
              <span>Drag and drop your .env file here or tap to browse.</span>
            </span>

            <Badge className="rounded-full px-3 py-0.5" variant="outline">
              Drop Zone
            </Badge>
          </button>

          <input
            accept=".env,.txt"
            aria-label="Upload .env file"
            className="sr-only"
            id={fileUploadInputId}
            onChange={onEnvFileUpload}
            title="Upload .env file"
            type="file"
          />

          {uploadedFileName ? (
            <div className="space-y-2 rounded-xl border border-border/70 bg-background/70 p-3">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <Label className="font-medium text-[0.7rem] uppercase tracking-wider">
                  Uploaded File
                </Label>
                <Badge className="rounded-full px-3 py-0.5" variant="outline">
                  {uploadedFileName}
                </Badge>
              </div>

              <Textarea
                className="min-h-28 font-mono text-xs"
                readOnly
                value={bulkImportInput}
              />
            </div>
          ) : null}

          <Textarea
            className="min-h-28 font-mono text-xs"
            onChange={(event) => setBulkImportInput(event.target.value)}
            onPaste={onBulkImportPaste}
            placeholder="Paste KEY=VALUE lines here. Pasting auto-imports instantly."
            value={bulkImportInput}
          />

          <div className="grid gap-2 sm:grid-cols-[minmax(0,1fr)_auto]">
            <Button
              className="h-10 w-full rounded-xl border-primary/40 bg-primary/90 px-4 font-medium text-primary-foreground text-xs shadow-sm transition-colors hover:bg-primary"
              disabled={bulkImportInput.trim().length === 0}
              onClick={onImportFromTextarea}
              type="button"
              variant="default"
            >
              Import Text
            </Button>
            <Badge
              className="h-10 justify-center rounded-xl border-border/70 px-3 text-muted-foreground text-xs"
              variant="outline"
            >
              Paste auto-detect is enabled
            </Badge>
          </div>

          <p className="text-muted-foreground text-xs leading-5">
            Supports standard .env lines, optional export prefix, comments, and
            quoted values.
          </p>
        </div>

        {importMessage ? (
          <Alert className="border-primary/30 bg-primary/5">
            <ShieldCheck className="size-4 text-primary" weight="fill" />
            <AlertTitle>Environment variables imported</AlertTitle>
            <AlertDescription>{importMessage}</AlertDescription>
          </Alert>
        ) : null}

        {variables.map((variable, index) => (
          <div
            className="grid grid-cols-1 gap-2 sm:grid-cols-[minmax(0,0.85fr)_minmax(0,1.15fr)_auto_auto]"
            key={variable.id}
          >
            <Input
              aria-label={`Variable ${String(index + 1)} key`}
              className="h-10 font-mono text-xs"
              placeholder="KEY_NAME"
              readOnly
              value={variable.key}
            />
            <Input
              aria-label={`Variable ${String(index + 1)} value`}
              className="h-10 flex-1 font-mono text-xs"
              placeholder="value"
              readOnly
              type={visibleVariableIds.has(variable.id) ? "text" : "password"}
              value={variable.value}
            />
            <Button
              aria-label={`Toggle visibility for variable ${String(index + 1)}`}
              className="h-10 w-10 rounded-xl border-border/70 bg-background/70 hover:bg-background"
              onClick={() => toggleVariableVisibility(variable.id)}
              type="button"
              variant="outline"
            >
              {visibleVariableIds.has(variable.id) ? (
                <EyeSlash className="size-4 text-muted-foreground" />
              ) : (
                <Eye className="size-4 text-muted-foreground" />
              )}
            </Button>
            <Button
              aria-label={`Remove variable ${String(index + 1)}`}
              className="h-10 w-10 rounded-xl border-border/70 bg-background/70 hover:bg-background"
              onClick={() => onRemoveVariable(variable.id)}
              type="button"
              variant="outline"
            >
              <Trash className="size-4 text-muted-foreground" />
            </Button>
          </div>
        ))}

        {variables.length === 0 ? (
          <div className="rounded-lg border border-border/70 bg-background/45 px-3 py-2 text-muted-foreground text-xs">
            No variables imported yet. Paste env lines or upload a .env file.
          </div>
        ) : null}
      </div>

      <p className="text-muted-foreground text-xs leading-5">
        Imported rows are locked to prevent accidental edits. Delete and
        re-import to change values.
      </p>
    </div>
  );
}

function EncryptForm() {
  const [variables, setVariables] = useState<EnvVariable[]>([]);
  const [passphrase, setPassphrase] = useState("");
  const [showPassphrase, setShowPassphrase] = useState(false);
  const [ttlMinutes, setTtlMinutes] = useState("15");
  const [state, setState] = useState<EncryptionState>("idle");
  const [resultId, setResultId] = useState<string | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [validationMessage, setValidationMessage] = useState<string | null>(
    null
  );
  const {
    bulkImportInput,
    handleDroppedEnvFile,
    handleBulkImportPaste,
    handleEnvFileUpload,
    handleImportFromTextarea,
    importMessage,
    resetBulkImportState,
    setBulkImportInput,
    uploadedFileName,
  } = useBulkEnvImport({
    setValidationMessage,
    setVariables,
  });

  useEffect(() => {
    setPassphrase(generateSecurePassphrase());
  }, []);

  const removeVariable = useCallback((id: string) => {
    setVariables((prev) => prev.filter((v) => v.id !== id));
    setValidationMessage(null);
  }, []);

  const handleRegeneratePassphrase = useCallback(() => {
    setPassphrase(generateSecurePassphrase());
    setValidationMessage(null);
  }, []);

  const handleDeletePassphrase = useCallback(() => {
    setPassphrase("");
    setShowPassphrase(false);
    setValidationMessage(null);
  }, []);

  const handleCopyPassphrase = useCallback(async () => {
    if (passphrase.length === 0) {
      return;
    }

    try {
      await navigator.clipboard.writeText(passphrase);
    } catch {
      // Ignore clipboard failures.
    }
  }, [passphrase]);

  const passphraseStrength = getPassphraseStrength(passphrase);
  const duplicateKeys = getDuplicateVariableKeys(variables);
  const hasValidVariables = variables.some(
    (v) => v.key.trim().length > 0 && v.value.trim().length > 0
  );
  const hasValidPassphrase = passphrase.length >= MIN_PASSPHRASE_LENGTH;
  const canEncrypt =
    hasValidVariables &&
    hasValidPassphrase &&
    duplicateKeys.length === 0 &&
    state !== "encrypting";
  const strengthToneClass = getStrengthToneClass(passphraseStrength.label);

  const handleEncrypt = useCallback(async () => {
    const validationError = getEncryptValidationMessage(
      duplicateKeys,
      canEncrypt
    );
    if (validationError) {
      setValidationMessage(validationError);
      return;
    }

    setState("encrypting");
    setErrorMessage(null);
    setValidationMessage(null);
    setResultId(null);

    try {
      const envMap = buildEnvironmentMap(variables);
      if (Object.keys(envMap).length === 0) {
        setValidationMessage(
          "No complete environment variables were provided."
        );
        setState("idle");
        return;
      }

      const envelope = await createEnvironmentEnvelope(envMap, passphrase, {
        kdf: getKdfConfiguration(),
      });

      const envelopeJson = JSON.stringify(envelope);
      const ttlSeconds =
        ttlMinutes === "0" ? undefined : Number(ttlMinutes) * 60;

      const result = await storeEnvelopeFromClientAction(
        envelopeJson,
        ttlSeconds,
        true
      );

      if (result.success && result.id) {
        setResultId(result.id);
        setState("done");
      } else {
        setErrorMessage(result.error ?? "Failed to store envelope.");
        setState("error");
      }
    } catch (error) {
      const message =
        error instanceof Error ? error.message : "Encryption failed.";
      setErrorMessage(message);
      setState("error");
    }
  }, [canEncrypt, duplicateKeys, variables, passphrase, ttlMinutes]);

  const handleReset = useCallback(() => {
    setVariables([]);
    resetBulkImportState();
    setPassphrase(generateSecurePassphrase());
    setShowPassphrase(false);
    setTtlMinutes("15");
    setState("idle");
    setResultId(null);
    setErrorMessage(null);
    setValidationMessage(null);
  }, [resetBulkImportState]);

  if (state === "done" && resultId) {
    const shareUrl =
      typeof window === "undefined"
        ? `/s/${resultId}`
        : `${window.location.origin}/s/${resultId}`;

    return (
      <Card className="vault-glass relative animate-vault-fade-in overflow-hidden border-primary/25">
        <div className="pointer-events-none absolute inset-x-0 top-0 h-20 bg-linear-to-b from-primary/12 to-transparent" />
        <CardContent className="flex flex-col items-center gap-6 py-8 text-center">
          <div className="flex size-16 animate-vault-pulse-glow items-center justify-center rounded-full bg-primary/15">
            <ShieldCheck className="size-8 text-primary" weight="duotone" />
          </div>

          <div className="space-y-2">
            <h3 className="font-semibold text-xl">Envelope Sealed</h3>
            <p className="text-muted-foreground text-sm">
              Your environment variables are encrypted and stored securely.
            </p>
          </div>

          <Alert className="max-w-md border-primary/30 bg-primary/5 text-left">
            <ShieldCheck className="size-4 text-primary" weight="fill" />
            <AlertTitle>
              Envelope stored with zero-knowledge guarantees
            </AlertTitle>
            <AlertDescription>
              Share the link and passphrase separately for safer delivery.
            </AlertDescription>
          </Alert>

          <div className="w-full max-w-md space-y-4">
            <div className="block space-y-2 text-left">
              <Label className="text-muted-foreground text-xs uppercase tracking-wider">
                Envelope ID
              </Label>
              <div className="flex items-center gap-2">
                <code className="flex-1 rounded-lg border border-border bg-background px-3 py-2 font-mono text-sm">
                  {resultId}
                </code>
                <CopyButton label="Copy ID" value={resultId} />
              </div>
            </div>

            <div className="block space-y-2 text-left">
              <Label className="text-muted-foreground text-xs uppercase tracking-wider">
                Share Link
              </Label>
              <div className="flex items-center gap-2">
                <code className="flex-1 truncate rounded-lg border border-border bg-background px-3 py-2 font-mono text-xs">
                  {shareUrl}
                </code>
                <CopyButton label="Copy" value={shareUrl} />
              </div>
            </div>
          </div>

          <Separator className="max-w-md" />

          <div className="flex flex-wrap justify-center gap-2">
            <Badge variant="outline">One-time use</Badge>
            <Badge variant="outline">
              TTL: {ttlMinutes === "0" ? "No expiry" : `${ttlMinutes}m`}
            </Badge>
            <Badge variant="default">Argon2id</Badge>
          </div>

          <p className="max-w-md text-muted-foreground text-xs leading-5">
            This link can be opened only once. After retrieval, it cannot be
            opened again.
          </p>

          <Button className="mt-2" onClick={handleReset} variant="secondary">
            Encrypt Another
          </Button>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="vault-glass relative animate-vault-fade-in overflow-hidden border-primary/20">
      <div className="pointer-events-none absolute inset-x-0 top-0 h-28 bg-linear-to-b from-primary/10 to-transparent" />
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Lock className="size-5 text-primary" weight="duotone" />
          Encrypt &amp; Share
        </CardTitle>
        <p className="text-muted-foreground text-sm">
          Configure your envelope, then seal it locally in your browser.
        </p>
      </CardHeader>

      <CardContent className="space-y-7">
        <EnvironmentVariablesSection
          bulkImportInput={bulkImportInput}
          importMessage={importMessage}
          onBulkImportPaste={handleBulkImportPaste}
          onDroppedEnvFile={handleDroppedEnvFile}
          onEnvFileUpload={handleEnvFileUpload}
          onImportFromTextarea={handleImportFromTextarea}
          onRemoveVariable={removeVariable}
          setBulkImportInput={setBulkImportInput}
          uploadedFileName={uploadedFileName}
          variables={variables}
        />

        <Separator />

        {/* Passphrase */}
        <div className="space-y-4 rounded-2xl border border-border/80 bg-card/60 p-5 md:p-6">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <Label className="font-medium text-sm" htmlFor="passphrase-input">
              <Key
                className="mr-1 inline-block size-4 text-primary"
                weight="duotone"
              />
              Passphrase
            </Label>

            <div className="flex flex-wrap items-center gap-2">
              <Badge className="rounded-full px-3 py-0.5" variant="default">
                Auto-generated
              </Badge>
              <Badge
                className="rounded-full border-primary/35 px-3 py-0.5"
                variant="outline"
              >
                Locked
              </Badge>
              <Badge className="rounded-full px-3 py-0.5" variant="secondary">
                Min 12 chars
              </Badge>
            </div>
          </div>

          <div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-[minmax(0,1fr)_auto_auto_auto]">
            <div className="relative">
              <Input
                className="h-10 pr-10 font-mono text-xs"
                id="passphrase-input"
                minLength={MIN_PASSPHRASE_LENGTH}
                placeholder="Minimum 12 characters"
                readOnly
                type={showPassphrase ? "text" : "password"}
                value={passphrase}
              />
              <button
                aria-label={
                  showPassphrase ? "Hide passphrase" : "Show passphrase"
                }
                className="absolute top-1/2 right-2.5 -translate-y-1/2 text-muted-foreground transition-colors hover:text-foreground"
                onClick={() => setShowPassphrase((p) => !p)}
                type="button"
              >
                {showPassphrase ? (
                  <EyeSlash className="size-4" />
                ) : (
                  <Eye className="size-4" />
                )}
              </button>
            </div>

            <Button
              className="h-10 w-full gap-2 rounded-xl px-4 sm:w-auto"
              onClick={handleRegeneratePassphrase}
              type="button"
              variant="secondary"
            >
              <ArrowsClockwise className="size-4" weight="bold" />
              Regenerate
            </Button>

            <Button
              className="h-10 w-full gap-2 rounded-xl px-4 sm:w-auto"
              onClick={handleCopyPassphrase}
              type="button"
              variant="outline"
            >
              <Copy className="size-4" weight="bold" />
              Copy
            </Button>

            <Button
              className="h-10 w-full gap-2 rounded-xl px-4 sm:w-auto"
              onClick={handleDeletePassphrase}
              type="button"
              variant="outline"
            >
              <Trash className="size-4" weight="bold" />
              Delete
            </Button>
          </div>

          {passphrase.length > 0 ? (
            <div className="space-y-2">
              <Progress className="h-1.5" value={passphraseStrength.percent} />
              <div className="flex items-center justify-between">
                <span className="text-muted-foreground text-xs">
                  Strength meter
                </span>
                <span className={`font-medium text-xs ${strengthToneClass}`}>
                  {passphraseStrength.label}
                </span>
              </div>
            </div>
          ) : null}

          <p className="text-muted-foreground text-xs leading-5">
            Passphrase is managed for you to reduce accidental mistakes. Use
            regenerate if you need a new one and share it separately from the
            link.
          </p>
        </div>

        {/* Options row */}
        <div className="space-y-4 rounded-2xl border border-border/80 bg-card/60 p-5 md:p-6">
          <Label className="font-medium text-sm">Envelope Options</Label>

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <div className="space-y-1.5">
              <Label
                className="text-muted-foreground text-xs"
                htmlFor="kdf-profile"
              >
                KDF Profile
              </Label>
              <div
                className="flex h-10 items-center rounded-md border border-input bg-muted/30 px-3"
                id="kdf-profile"
              >
                <span className="font-medium text-sm">Argon2id (locked)</span>
              </div>
              <p className="text-muted-foreground text-xs">
                The app always uses Argon2id for new envelopes.
              </p>
            </div>

            <div className="space-y-1.5">
              <Label
                className="text-muted-foreground text-xs"
                htmlFor="expires-after"
              >
                Expires after
              </Label>
              <Select onValueChange={setTtlMinutes} value={ttlMinutes}>
                <SelectTrigger className="w-full" id="expires-after">
                  <SelectValue placeholder="Select TTL" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="5">5 minutes</SelectItem>
                  <SelectItem value="15">15 minutes</SelectItem>
                  <SelectItem value="30">30 minutes</SelectItem>
                  <SelectItem value="60">1 hour</SelectItem>
                  <SelectItem value="1440">24 hours</SelectItem>
                  <SelectItem value="0">No expiry</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <Alert className="border-primary/30 bg-primary/5">
            <ShieldCheck className="size-4 text-primary" weight="fill" />
            <AlertTitle>One-time retrieval is always enabled</AlertTitle>
            <AlertDescription>
              Every new envelope link can be opened only once.
            </AlertDescription>
          </Alert>
        </div>

        {duplicateKeys.length > 0 ? (
          <Alert
            className="border-destructive/35 bg-destructive/10"
            variant="destructive"
          >
            <Warning className="size-4" weight="fill" />
            <AlertTitle>Duplicate environment keys</AlertTitle>
            <AlertDescription>
              {duplicateKeys.slice(0, 4).join(", ")}
              {duplicateKeys.length > 4 ? "..." : ""}
            </AlertDescription>
          </Alert>
        ) : null}

        {validationMessage ? (
          <Alert
            className="border-destructive/35 bg-destructive/10"
            variant="destructive"
          >
            <Warning className="size-4" weight="fill" />
            <AlertTitle>Review your inputs</AlertTitle>
            <AlertDescription>{validationMessage}</AlertDescription>
          </Alert>
        ) : null}

        {/* Error message */}
        {errorMessage ? (
          <Alert
            className="border-destructive/35 bg-destructive/10"
            variant="destructive"
          >
            <Warning className="size-4" weight="fill" />
            <AlertTitle>Could not seal envelope</AlertTitle>
            <AlertDescription>{errorMessage}</AlertDescription>
          </Alert>
        ) : null}

        {/* Encrypt button */}
        <Button
          className="w-full gap-2"
          disabled={!canEncrypt}
          onClick={handleEncrypt}
          size="lg"
          type="button"
        >
          {state === "encrypting" ? (
            <>
              <span className="inline-block size-4 animate-spin rounded-full border-2 border-current border-t-transparent" />
              Encrypting…
            </>
          ) : (
            <>
              <Lock className="size-4" weight="bold" />
              Encrypt &amp; Seal
            </>
          )}
        </Button>

        <p className="text-center text-muted-foreground text-xs leading-5">
          Encryption happens entirely in your browser. Your passphrase and
          plaintext values never leave this device.
        </p>
      </CardContent>
    </Card>
  );
}

export { EncryptForm };
